version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-innotech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innotechfusion
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend-innotech
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - innotech-net
  frontend:
    build:
      context: ./frontend
    container_name: frontend-innotech
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - innotech-net

volumes:
  db_data:

networks:
  innotech-net:
